### ISSUE TITLE
value of contact tracing?

### ISSUE THREAD

**Issue by mikkokotila** [kausaltech/reina-model#23]
The consensus at the moment is that contact tracing matters. But does it?

For example, the area where I live has around 30k inhabitants, but the local hospital according to the staff does not have a single COVID-19 case. Yet a large number of people commute daily to one of  Finland's three largest cities. We know that Helsinki has had the virus circulating for some months, and US has a large number of counties that do not have any cases. How come it did not yield a single case in this area if it is so contagious? At the same time, we know that cross-border contamination is very effective (airplanes, airports, airport busses, hotels that circulate air, etc).

Maybe it is highly contagious, but only when certain "density" of exposure is met.  Maybe the main vector is a gas exchange and not droplets. 

Can we get some contract tracing data to analyze?

**Comment by mikkokotila** [comment]
Related with this is the mistake everyone seems to follow, which is to say that the virus has a unitary contagion profile. But instead, I think it is better to think in terms of the context, maybe:

- global
- regional
- national
- local
- neighborhood
- family

Maybe it is contagious really different depending on the context. Which makes mitigating it far more approachable, than when we just assume that it is highly contagious. For example, if we know that gas exchange is a big thing, buildings can improve air ventilation, global travel can be minimized for some time, and special groups like old folk homes, ethical minorities, and so forth, can be considered more actively.

**Comment by juyrjola** [comment]
Contact tracing seems to be the key component with which countries such as South Korea and China have gotten the raging epidemic under control. According to our simulation, being able to locate potentially infectious individuals early and isolate them is very helpful getting the Rt lower.

The current understanding is that SARS-CoV-2 needs some time ("close contact") in order to have a high enough probability to spread. There are notable examples of wide spreading happening in cases such as [a choir rehearsal](https://edition.cnn.com/2020/04/01/us/washington-choir-practice-coronavirus-deaths/index.html), where people use their vocal chords and expel massive amounts of particles from their throats. If a person has viral matter in their throat, the particles will include active virus. Breathing out forcefully – like in singing, preaching or speaking loudly – will also spread the particles wide.

Having no detected cases might not mean having zero actual cases. We assume that 50 % of carriers are asymptomatic.

We believe the contagiousness of the virus is fairly high and the fatality is about 10 times that of influenza. There is another hypothesis that assumes the virus spreads like wildfire but is less dangerous. The experience in your home town would be more in line with the former hypothesis, because if the virus really were super-contagious, there would most likely be confirmed cases in your town, too.

**Comment by juyrjola** [comment]
If the "wildfire" hypothesis were correct, then using contact tracing measures shouldn't have a big impact in being able to contain the spread.

**Comment by juyrjola** [comment]
There is [research](https://www.nature.com/articles/s41598-019-38808-z) suggesting people differ a lot in how many particles they emit in general, and that emission increases with the loudness of vocalization.

The key findings from the article:

> 1. The particle emission rate during speech is linearly correlated with the amplitude (loudness) of vocalization, for four different languages tested.
> 2. The particle size distribution is independent of vocalization loudness or language spoken.
> 3. Some individuals emit particles at a rate more than an order of magnitude larger than their peers, i.e., they behave as “speech superemitters.”

**Comment by juyrjola** [comment]
Theri is another article, [Understanding and Modeling the Super-spreading Events of the Middle East Respiratory Syndrome Outbreak in Korea](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4945728/), that implies that the so-called super-spreaders might play a considerable role in epidemic spread.

**Comment by juyrjola** [comment]
If this were the case, finding and isolating these super-spreaders would be a good way to contain epidemic spread.

**Comment by juyrjola** [comment]
On another note, a recent article in Nature Medicine called [Respiratory virus shedding in exhaled breath and efficacy of face masks](https://www.nature.com/articles/s41591-020-0843-2) found that simple surgical masks are an effective way to limit the number of droplets and aerosols an infected person emits. And even if some particles pass through the mask, their kinetic energy is probably reduced so much that they will not spread far.

**Comment by mikkokotila** [comment]
> If the "wildfire" hypothesis were correct, then using contact tracing measures shouldn't have a big impact in being able to contain the spread.

Precisely. At the moment China is very difficult to say about; they used several harsh mitigation measures, and it's still unclear what is the actual situation there at the moment. South Korea and Taiwan could be flukes. It would be very interesting to see South Korea and Taiwan tracing data to know how many infected are found through the tracing activity.

> If this were the case, finding and isolating these super-spreaders would be a good way to contain epidemic spread.

+1

**Comment by mikkokotila** [comment]
I think we concluded here so closing :)
